const fieldNames = {
   passengerType: 'passengerType',
   lastName: 'lastName',
   firstName: 'firstName',
   fathersName: 'fathersName',
   gender: 'gender',
   dateOfBirth: 'dateOfBirth',
   specialNeeds: 'specialNeeds',
   docType: 'documentType',
   docSerialNumber: 'documentSerialNumber',
   docNumberPass: 'documentNumber',
   docNumberSertif: 'documentNumber',
   seatDep: 'seatDep',
   seatArr: 'seatArr',
   depOnly: 'departureOnly',
   lastNameLabel: ' Фамилия',
   firstNameLabel: 'Имя',
   fathersNameLabel: 'Отчество',
   genderLabel: 'Пол',
   dateOfBirthLabel: 'Дата рождения',
   specialNeedsLabel: 'ограниченная подвижность',
   docTypeLabel: 'Тип документа',
   docSerialNumberLabel: 'Серия',
   docNumberPassLabel: 'Номер',
   docNumberSertifLabel: 'Номер',
   seatDepLabel: 'Место туда',
   depOnlyLabel: 'Только туда',
   seatArrLabel: 'Место обратно',
};

export default fieldNames;
